kibot:
  version: 1

global:
  field_lcsc_part: LCSC

import:
  - file: JLCPCB
  - file: 3DRender_top
  - file: 3DRender_top_straight

preflight:
  erc:
    warnings_as_errors: true
  update_xml: true
  drc: false
  check_zone_fills: true

outputs:
  - name: 'ibom'
    comment: 'Interactive Bill of Materials'
    type: ibom
    dir: ibom

  - name: 'bom'
    comment: 'Bill of Materials'
    type: bom
    dir: bom
    options:
      csv:
        hide_pcb_info: true
        hide_stats_info: true
      format: CSV

  - name: 'html_bom'
    comment: 'HTML BOM'
    type: bom
    dir: html_bom
    options:
      html:
        datasheet_as_link: Datasheet
        digikey_link: Digikey
        title: 'Index MOBO Bill of Materials'

  - name: board_top
    comment: "Top layer view"
    type: pcbdraw
    options:
      format: png

  - name: board_bottom
    comment: "Bottom layer view"
    type: pcbdraw
    options:
      format: png
      bottom: true

  - name: 'step_file'
    comment: 'STEP file generation'
    type: step
    dir: step
