name: Kibot check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'pcb/**'
      - 'lib/kicad/**'


jobs:
  kibot_check:
    name: Check with Kibot
    runs-on: ubuntu-24.04
    if: always()

    strategy:
      matrix:
        pcbs: [bus, cm4, device_test, power, fm]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: check KiCad files
      uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: pcb/test.kibot.yaml
        dir: output
        schema: 'pcb/${{ matrix.pcbs }}/${{ matrix.pcbs }}.kicad_sch'
        verbose: 0
